export { default as Streak } from './Streak';
export { default as Kanban } from './Kanban';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Line } from './Charts/Line';
export { default as Login } from './Login';
export { default as Signin } from './Signin';
export { default as Dashboard } from './Dashboard';
//this helps with importing them in {} one-liner 
